// Generated by gencpp from file challenge/CustomMessage.msg
// DO NOT EDIT!


#ifndef CHALLENGE_MESSAGE_CUSTOMMESSAGE_H
#define CHALLENGE_MESSAGE_CUSTOMMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace challenge
{
template <class ContainerAllocator>
struct CustomMessage_
{
  typedef CustomMessage_<ContainerAllocator> Type;

  CustomMessage_()
    : number_1(0)
    , number_2(0)  {
    }
  CustomMessage_(const ContainerAllocator& _alloc)
    : number_1(0)
    , number_2(0)  {
  (void)_alloc;
    }



   typedef uint32_t _number_1_type;
  _number_1_type number_1;

   typedef uint32_t _number_2_type;
  _number_2_type number_2;




  typedef boost::shared_ptr< ::challenge::CustomMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::challenge::CustomMessage_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMessage_

typedef ::challenge::CustomMessage_<std::allocator<void> > CustomMessage;

typedef boost::shared_ptr< ::challenge::CustomMessage > CustomMessagePtr;
typedef boost::shared_ptr< ::challenge::CustomMessage const> CustomMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::challenge::CustomMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::challenge::CustomMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace challenge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'challenge': ['/home/justin/gits/rosttest/catkin_ws/src/challenge/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::challenge::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::challenge::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::challenge::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::challenge::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::challenge::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::challenge::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::challenge::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a943712877e7ef9d7005faad2d1b0651";
  }

  static const char* value(const ::challenge::CustomMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa943712877e7ef9dULL;
  static const uint64_t static_value2 = 0x7005faad2d1b0651ULL;
};

template<class ContainerAllocator>
struct DataType< ::challenge::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "challenge/CustomMessage";
  }

  static const char* value(const ::challenge::CustomMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::challenge::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 number_1\n\
uint32 number_2\n\
";
  }

  static const char* value(const ::challenge::CustomMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::challenge::CustomMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number_1);
      stream.next(m.number_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::challenge::CustomMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::challenge::CustomMessage_<ContainerAllocator>& v)
  {
    s << indent << "number_1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number_1);
    s << indent << "number_2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHALLENGE_MESSAGE_CUSTOMMESSAGE_H
